import AppShell, { Workspace } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Bot, CalendarClock, Pause, Play, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";

export default function Automations({ business }: { business: Workspace }) {
  const { data, isLoading, error } = trpc.automation.list.useQuery({ businessId: business.id }); const utils = trpc.useUtils(); const refresh = () => utils.automation.list.invalidate({ businessId: business.id });
  const create = trpc.automation.createWeeklySummary.useMutation({ onSuccess: result => { refresh(); toast.success(result.nextExecutionAt ? "Automatisation planifiée." : "Automatisation créée."); }, onError: () => toast.error("La création de l’automatisation a échoué. Vérifiez que le site est publié.") });
  const toggle = trpc.automation.toggle.useMutation({ onSuccess: () => { refresh(); toast.success("Automatisation mise à jour."); }, onError: () => toast.error("La mise à jour de l’automatisation a échoué.") });
  const remove = trpc.automation.remove.useMutation({ onSuccess: () => { refresh(); toast.success("Automatisation supprimée."); }, onError: () => toast.error("La suppression de l’automatisation a échoué.") });
  return <AppShell business={business} title="Automatisations"><div className="cb-page"><section className="cb-page-intro"><div><p className="cb-eyebrow">Gagner du temps</p><h2>Automatisations</h2><p>Programmez les rappels utiles. Les tâches sont exécutées de façon fiable après publication de votre site.</p></div><Button onClick={() => create.mutate({ businessId: business.id })} disabled={create.isPending}><Plus size={17} /> Ajouter un point hebdomadaire</Button></section><section className="cb-automation-explainer"><Bot size={22} /><div><strong>Point hebdomadaire</strong><p>Chaque lundi à 09:00, heure de La Réunion, une notification récapitule les commandes de la semaine.</p></div></section>{isLoading ? <div className="cb-table-skeleton" /> : error ? <section className="cb-empty"><span><CalendarClock size={25} /></span><h3>Les automatisations sont indisponibles.</h3><p>Réessayez dans quelques instants.</p><Button variant="outline" onClick={refresh}>Réessayer</Button></section> : data?.length ? <div className="cb-automation-list">{data.map(rule => <article key={rule.id}><span className="cb-automation-icon"><CalendarClock size={19} /></span><div><h3>{rule.name}</h3><p>{String(rule.triggerConfig.cadence || "Planification")} · {rule.isEnabled ? "Active" : "En pause"}</p></div><Badge variant={rule.isEnabled ? "default" : "secondary"}>{rule.isEnabled ? "Active" : "En pause"}</Badge><Button variant="outline" size="sm" disabled={toggle.isPending} onClick={() => toggle.mutate({ businessId: business.id, id: rule.id, isEnabled: !rule.isEnabled })}>{rule.isEnabled ? <><Pause size={14} /> Mettre en pause</> : <><Play size={14} /> Reprendre</>}</Button><Button variant="ghost" size="icon" disabled={remove.isPending} className="text-destructive" onClick={() => { if (window.confirm("Supprimer cette automatisation ?")) remove.mutate({ businessId: business.id, id: rule.id }); }}><Trash2 size={16} /></Button></article>)}</div> : <section className="cb-empty"><span><CalendarClock size={25} /></span><h3>Pas encore d’automatisation.</h3><p>Commencez par un point hebdomadaire pour garder le rythme sans y penser.</p><Button onClick={() => create.mutate({ businessId: business.id })} disabled={create.isPending}><Plus size={17} /> Ajouter un point hebdomadaire</Button></section>}</div></AppShell>;
}
