import AppShell, { Workspace } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { money, shortDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Mail, Search, Users } from "lucide-react";
import { useState } from "react";
import { CustomerDetails } from "@/components/CommerceDetails";

export default function Customers({ business }: { business: Workspace }) { const [query, setQuery] = useState(""); const { data, isLoading, error } = trpc.customer.list.useQuery({ businessId: business.id, query: query || undefined }); const utils = trpc.useUtils(); return <AppShell business={business} title="Clients"><div className="cb-page"><section className="cb-page-intro"><div><p className="cb-eyebrow">Relation client</p><h2>Vos clients</h2><p>Retrouvez leur historique et mesurez leur fidélité.</p></div></section><div className="cb-toolbar"><div className="cb-search"><Search size={17} /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Nom ou e-mail" /></div></div>{isLoading ? <div className="cb-table-skeleton" /> : error ? <section className="cb-empty"><span><Users size={25} /></span><h3>Les clients sont indisponibles.</h3><p>Réessayez dans quelques instants.</p><Button variant="outline" onClick={() => utils.customer.list.invalidate()}>Réessayer</Button></section> : data?.length ? <div className="cb-customer-grid">{data.map(customer => <article key={customer.id} className="cb-customer-card"><div className="cb-avatar">{customer.firstName[0]}{customer.lastName[0]}</div><div><h3>{customer.firstName} {customer.lastName}</h3><p><Mail size={13} /> {customer.email}</p><small>{customer.phone || "Téléphone non renseigné"} · Client depuis le {shortDate(customer.createdAt)}</small></div><dl><div><dt>Commandes</dt><dd>{customer.orderCount}</dd></div><div><dt>Valeur</dt><dd>{money(customer.lifetimeValueCents)}</dd></div></dl><div className="cb-customer-detail-action"><CustomerDetails businessId={business.id} customerId={customer.id} /></div></article>)}</div> : <section className="cb-empty"><span><Users size={25} /></span><h3>Votre base client se construit ici.</h3><p>Chaque commande reçue depuis votre boutique ajoute automatiquement un client.</p></section>}</div></AppShell>; }
