import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, BarChart3, Bot, Check, ChevronRight, ClipboardList, Menu, Package, Sparkles, Store, Users } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const features = [
  { icon: Store, title: "Une vitrine qui vous ressemble", text: "Présentez votre activité, vos produits et vos coordonnées avec une boutique partageable." },
  { icon: ClipboardList, title: "Vos commandes, au bon endroit", text: "Recevez et suivez chaque demande sans multiplier les messages ni les tableaux." },
  { icon: BarChart3, title: "Une vision claire de l’activité", text: "Repérez les commandes, les produits demandés et les actions qui comptent." },
  { icon: Bot, title: "L’IA au service du quotidien", text: "Améliorez vos contenus et identifiez les priorités sans jargon ni gadget." },
];

const faqs = [
  { question: "À qui s’adresse CommerceBoost974 ?", answer: "La plateforme est conçue pour les artisans, commerçants, indépendants et TPE de La Réunion qui souhaitent gérer une présence en ligne sans multiplier les outils." },
  { question: "Puis-je créer ma boutique sans compétence technique ?", answer: "Oui. Le parcours guidé vous accompagne de la présentation de votre activité jusqu’au premier produit et à la publication de la boutique." },
  { question: "Comment les commandes sont-elles gérées ?", answer: "Le client compose son panier dans votre boutique. Les prix et promotions sont recalculés côté serveur, puis la demande arrive dans votre espace pour être confirmée et suivie." },
  { question: "L’assistant IA remplace-t-il mes décisions ?", answer: "Non. Il prépare des propositions de contenu ou de synthèse que vous relisez et modifiez librement. Les décisions de publication restent toujours les vôtres." },
];

export default function Home() {
  const { isAuthenticated } = useAuth();
  const [menu, setMenu] = useState(false);
  const enter = () => isAuthenticated ? window.location.assign("/app") : startLogin();
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "CommerceBoost974", applicationCategory: "BusinessApplication", operatingSystem: "Web", description: "Vitrine, catalogue, commandes et pilotage pour les artisans, commerçants et TPE de La Réunion." };
  return <div className="cb-marketing">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="cb-marketing-nav"><Link href="/" className="cb-brand"><span className="cb-brand-mark">C</span>CommerceBoost<span className="cb-brand-accent">974</span></Link><nav className={menu ? "is-open" : ""}><a href="#solution" onClick={() => setMenu(false)}>La solution</a><a href="#fonctionnalites" onClick={() => setMenu(false)}>Fonctionnalités</a><a href="#tarifs" onClick={() => setMenu(false)}>Tarifs</a></nav><div className="cb-nav-ctas"><button className="cb-text-button" onClick={enter}>Se connecter</button><Button onClick={enter}>Créer mon espace <ArrowRight size={16} /></Button></div><button className="cb-mobile-nav" onClick={() => setMenu(value => !value)} aria-label="Ouvrir le menu"><Menu size={21} /></button></header>
    <main>
      <section className="cb-hero" id="solution"><div className="cb-hero-copy"><p className="cb-pill"><Sparkles size={14} /> Pensé pour les entreprises réunionnaises</p><h1>Développez votre activité avec le <em>numérique</em> et l’IA.</h1><p>CommerceBoost974 réunit votre vitrine, vos commandes, vos clients et les informations utiles pour avancer simplement.</p><div className="cb-hero-actions"><Button size="lg" onClick={enter}>Créer mon espace <ArrowRight size={18} /></Button><a href="#fonctionnalites" className="cb-quiet-link">Découvrir CommerceBoost974 <ChevronRight size={16} /></a></div><div className="cb-proof-line"><Check size={15} /> Sans compétence technique <Check size={15} /> Depuis La Réunion, pour La Réunion</div></div><Preview /></section>
      <section className="cb-value" id="fonctionnalites"><div className="cb-section-title"><p className="cb-eyebrow">Une plateforme, plusieurs besoins</p><h2>Le bon outil pour faire avancer une petite entreprise.</h2><p>Une expérience simple à prendre en main, sans sacrifier la rigueur de gestion.</p></div><div className="cb-feature-grid">{features.map(feature => <article key={feature.title}><span><feature.icon size={21} /></span><h3>{feature.title}</h3><p>{feature.text}</p><a href="#comment-ca-marche">En savoir plus <ArrowRight size={14} /></a></article>)}</div></section>
      <section className="cb-workflow" id="comment-ca-marche"><div className="cb-workflow-copy"><p className="cb-eyebrow">Simple du premier jour au quotidien</p><h2>Créez, publiez, pilotez.</h2><p>Le parcours vous guide depuis votre activité jusqu’à votre première commande, puis garde les informations importantes à portée de main.</p><ul><li><span>01</span> Créez votre espace professionnel.</li><li><span>02</span> Ajoutez vos produits et publiez votre boutique.</li><li><span>03</span> Gérez vos commandes et votre activité.</li></ul></div><div className="cb-workflow-card"><div className="cb-ai-mark"><Bot size={20} /> Assistant métier</div><h3>Une aide intégrée aux bonnes étapes.</h3><p>Des suggestions pour améliorer une description, préparer une offre ou repérer une action utile.</p><div><span>Améliorer la description</span><span className="is-selected">Suggérer une promotion</span><span>Faire le point sur la semaine</span></div></div></section>
      <section className="cb-segments"><div><p className="cb-eyebrow">Pour celles et ceux qui font vivre l’île</p><h2>Une base solide, adaptée à votre réalité.</h2></div><div className="cb-segment-list"><article><Package size={20} /><h3>Artisans</h3><p>Montrez votre savoir-faire et prenez des commandes sans vous disperser.</p></article><article><Store size={20} /><h3>Commerçants</h3><p>Gardez votre catalogue, vos offres et vos clients sous contrôle.</p></article><article><Users size={20} /><h3>TPE</h3><p>Alignez les informations utiles pour piloter votre activité avec sérénité.</p></article></div></section>
      <section className="cb-pricing" id="tarifs"><div className="cb-section-title"><p className="cb-eyebrow">Des offres adaptées</p><h2>Starter, Business et Pro.</h2><p>Les capacités de chaque offre sont appliquées côté serveur. Les tarifs et conditions seront publiés après création des produits et prix réels dans Stripe.</p></div><div className="cb-pricing-card"><div><strong>Configuration commerciale en cours</strong><p>Starter couvre la présence en ligne, Business ajoute catalogue, commandes et analytics, et Pro ajoute IA et automatisations. Aucun prix ni essai n’est affiché tant qu’il n’est pas configuré dans Stripe.</p></div><span>La souscription reste désactivée jusqu’à la configuration Stripe réelle</span></div></section>
      <section className="max-w-5xl mx-auto px-5 pb-24"><div className="cb-section-title"><p className="cb-eyebrow">Questions fréquentes</p><h2>Ce qu’il faut savoir avant de commencer.</h2></div><div className="grid gap-3 mt-10">{faqs.map(item => <details key={item.question} className="rounded-2xl bg-white/80 border border-emerald-950/10 px-5 py-4 group"><summary className="cursor-pointer list-none font-semibold text-emerald-950 flex items-center justify-between">{item.question}<ChevronRight size={18} className="transition-transform group-open:rotate-90" /></summary><p className="mt-3 text-slate-600 leading-7 max-w-3xl">{item.answer}</p></details>)}</div></section>
      <section className="cb-final-cta"><div><p className="cb-eyebrow">Prêt à commencer ?</p><h2>Votre activité mérite un espace aussi sérieux que votre travail.</h2></div><Button size="lg" onClick={enter}>Créer mon espace CommerceBoost974 <ArrowRight size={18} /></Button></section>
    </main>
    <footer className="cb-footer"><Link href="/" className="cb-brand"><span className="cb-brand-mark">C</span>CommerceBoost<span className="cb-brand-accent">974</span></Link><span>Le copilote numérique des professionnels réunionnais.</span><div><span>Contact à renseigner avant publication</span><Link href="/confidentialite">Confidentialité</Link><Link href="/mentions-legales">Mentions légales</Link><Link href="/cgu">CGU</Link><Link href="/cgv">CGV</Link></div></footer>
  </div>;
}

function Preview() { return <div className="cb-product-preview" aria-label="Aperçu illustratif du tableau de bord"><div className="cb-preview-top"><span /><span /><span /></div><div className="cb-preview-sidebar"><b>CB<span>974</span></b><i /><i /><i /><i /></div><div className="cb-preview-content"><div className="cb-preview-heading"><span>Vue d’ensemble</span><small>Aperçu illustratif</small></div><div className="cb-preview-metrics"><div><small>Chiffre d’affaires</small><strong>—</strong><i /></div><div><small>Commandes</small><strong>—</strong><i /></div></div><div className="cb-preview-chart"><div>{[32, 48, 37, 65, 52, 78, 68, 92, 73, 88].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></div><div className="cb-preview-orders"><span>Votre activité, en un coup d’œil</span><div><b>Suivi des commandes</b><small>En temps réel</small><strong>—</strong></div><div><b>Produits populaires</b><small>À découvrir</small><strong>—</strong></div></div></div></div>; }
