import { Link } from "wouter";

const legalText = {
  privacy: { eyebrow: "Données et confidentialité", title: "Politique de confidentialité", intro: "CommerceBoost974 traite les données nécessaires à l’accès au service, à la gestion des espaces professionnels et au suivi des commandes créées dans les boutiques publiées.", sections: [["Données traitées", "Les données de compte, d’entreprise, de catalogue, de commande et de contact sont traitées uniquement pour fournir les fonctionnalités demandées, prévenir les usages frauduleux et sécuriser les accès."], ["Responsabilités", "Chaque entreprise est responsable des informations qu’elle publie et des données clients qu’elle collecte dans son espace. Les données de commande sont isolées par entreprise."], ["Vos droits et contact", "L’adresse de contact RGPD doit être renseignée par l’éditeur avant publication. Les demandes d’accès, de rectification, de suppression et d’export sont traitées après vérification de l’identité du demandeur."]] },
  legal: { eyebrow: "Informations légales", title: "Mentions légales", intro: "CommerceBoost974 est un service numérique destiné aux professionnels de La Réunion.", sections: [["Éditeur", "À renseigner avant publication : dénomination sociale, forme juridique, capital si applicable, adresse du siège, SIREN/RCS, numéro de TVA le cas échéant et moyen de contact."], ["Hébergement", "À renseigner avant publication : identité et coordonnées de l’hébergeur effectivement retenu."], ["Propriété intellectuelle", "Les contenus, marques et éléments graphiques de CommerceBoost974 sont protégés. Toute reproduction non autorisée est interdite."], ["Contact", "À renseigner avant publication : adresse e-mail de support et contact de l’éditeur."]] },
  terms: { eyebrow: "Conditions du service", title: "Conditions générales d’utilisation", intro: "Les présentes conditions encadrent l’accès au service CommerceBoost974 et à ses espaces professionnels.", sections: [["Accès au service", "Le professionnel conserve la responsabilité des personnes auxquelles il confie ses accès. Les identifiants de connexion sont personnels et ne doivent pas être partagés."], ["Contenus et obligations", "Le professionnel garantit la licéité, l’exactitude et les droits relatifs aux produits, contenus, promotions et informations clients qu’il utilise. Les usages contraires au droit, frauduleux ou portant atteinte aux tiers sont interdits."], ["Disponibilité et évolution", "Le service est fourni avec les mesures de sécurité et de continuité raisonnables. Des maintenances, correctifs ou évolutions peuvent intervenir afin d’améliorer la sécurité et le fonctionnement."], ["Données", "Chaque espace professionnel est isolé. Le titulaire peut exporter les données de son espace depuis les paramètres et demander les droits applicables en matière de données personnelles."], ["Droit applicable", "À compléter et valider par un conseil compétent avant publication : droit applicable, juridiction compétente et modalités de règlement des différends."]] },
  sales: { eyebrow: "Abonnement", title: "Conditions générales de vente", intro: "Ces conditions précisent le fonctionnement des abonnements CommerceBoost974 proposés aux professionnels.", sections: [["Offres et prix", "Les caractéristiques, limites et tarifs des offres Starter, Business et Pro sont présentés avant souscription. Les prix, taxes applicables et périodicité doivent être confirmés dans Stripe avant toute mise en production."], ["Paiement et renouvellement", "Les paiements et la gestion des moyens de paiement sont opérés par Stripe. L’abonnement est renouvelé selon la périodicité affichée lors du checkout, sauf résiliation avant la prochaine échéance."], ["Résiliation", "Le titulaire peut gérer ou résilier son abonnement via le portail de facturation. La suppression d’un espace professionnel ne constitue pas à elle seule une annulation de paiement auprès du prestataire de paiement."], ["Rétractation et clients professionnels", "À compléter et faire valider juridiquement avant publication en fonction du statut des clients, de l’offre et du régime légal applicable."], ["Support et litiges", "À compléter avant publication : coordonnées de support, médiation éventuelle, droit applicable et juridiction compétente."]] },
};

export default function Legal({ page }: { page: keyof typeof legalText }) { const content = legalText[page]; return <main className="min-h-screen bg-[#f5faf7] text-emerald-950"><header className="max-w-5xl mx-auto px-5 py-7"><Link href="/" className="cb-brand"><span className="cb-brand-mark">C</span>CommerceBoost<span className="cb-brand-accent">974</span></Link></header><article className="max-w-3xl mx-auto px-5 py-16"><p className="cb-eyebrow">{content.eyebrow}</p><h1 className="font-serif text-5xl leading-tight mt-3">{content.title}</h1><p className="text-lg text-slate-600 leading-8 mt-7">{content.intro}</p><div className="mt-12 space-y-9">{content.sections.map(([title, text]) => <section key={title}><h2 className="font-serif text-2xl">{title}</h2><p className="mt-3 text-slate-600 leading-8">{text}</p></section>)}</div><p className="mt-14 text-sm text-slate-500">Dernière mise à jour : 15 août 2026.</p></article></main>; }
