import AppShell, { Workspace } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { money } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Percent, Plus, Power } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function Promotions({ business }: { business: Workspace }) {
  const [open, setOpen] = useState(false); const { data, isLoading, error } = trpc.promotion.list.useQuery({ businessId: business.id }); const utils = trpc.useUtils();
  const toggle = trpc.promotion.toggle.useMutation({ onSuccess: () => { utils.promotion.list.invalidate(); toast.success("Promotion mise à jour."); } });
  return <AppShell business={business} title="Promotions"><div className="cb-page"><section className="cb-page-intro"><div><p className="cb-eyebrow">Booster vos ventes</p><h2>Promotions</h2><p>Créez des offres utiles, sur la bonne période, pour les bons produits.</p></div><PromotionDialog business={business} open={open} onOpenChange={setOpen} /></section>{isLoading ? <div className="cb-products-grid cb-loading-grid">{[1, 2].map(item => <div key={item} />)}</div> : error ? <section className="cb-empty"><span><Percent size={25} /></span><h3>Les promotions sont indisponibles.</h3><p>Réessayez dans quelques instants.</p><Button variant="outline" onClick={() => utils.promotion.list.invalidate({ businessId: business.id })}>Réessayer</Button></section> : data?.length ? <div className="cb-promo-grid">{data.map(promotion => <article key={promotion.id} className="cb-promo-card"><div className="cb-promo-symbol"><Percent size={22} /></div><div className="cb-promo-heading"><div><Badge variant={promotion.isActive ? "default" : "secondary"}>{promotion.isActive ? "Active" : "Désactivée"}</Badge><h3>{promotion.name}</h3></div><button aria-label="Activer ou désactiver" onClick={() => toggle.mutate({ businessId: business.id, id: promotion.id, isActive: !promotion.isActive })}><Power size={17} /></button></div><strong>{promotion.discountType === "percentage" ? `${promotion.discountValue} %` : money(promotion.discountValue)} <small>de réduction</small></strong><p><CalendarDays size={14} /> {promotion.startsAt ? `Dès le ${new Date(promotion.startsAt).toLocaleDateString("fr-FR")}` : "Disponible immédiatement"}</p><small>{promotion.appliesToAll ? "Toute la boutique" : "Produits sélectionnés"}{promotion.minimumOrderCents ? ` · minimum ${money(promotion.minimumOrderCents)}` : ""}</small></article>)}</div> : <section className="cb-empty"><span><Percent size={25} /></span><h3>Aucune promotion active.</h3><p>Proposez une offre claire pour encourager votre prochaine vente.</p><Button onClick={() => setOpen(true)}><Plus size={17} /> Créer une promotion</Button></section>}</div></AppShell>;
}

function PromotionDialog({ business, open, onOpenChange }: { business: Workspace; open: boolean; onOpenChange: (open: boolean) => void }) {
  const [form, setForm] = useState({ name: "", code: "", type: "percentage", value: "", minimum: "", startsAt: "", endsAt: "", productId: "all" }); const utils = trpc.useUtils();
  const { data: products = [] } = trpc.product.list.useQuery({ businessId: business.id, status: "active", sort: "name" }, { enabled: open });
  const create = trpc.promotion.create.useMutation({ onSuccess: () => { utils.promotion.list.invalidate(); toast.success("Promotion créée."); onOpenChange(false); setForm({ name: "", code: "", type: "percentage", value: "", minimum: "", startsAt: "", endsAt: "", productId: "all" }); } });
  const submit = (event: FormEvent) => { event.preventDefault(); const value = Number(form.value); const minimum = form.minimum ? Math.round(Number(form.minimum.replace(",", ".")) * 100) : null; if (!form.name || !Number.isFinite(value) || value <= 0) return toast.error("Indiquez un nom et une réduction valide."); if (form.type === "percentage" && value > 100) return toast.error("Une réduction ne peut pas dépasser 100 %."); const startsAt = form.startsAt ? new Date(`${form.startsAt}T00:00:00`) : null; const endsAt = form.endsAt ? new Date(`${form.endsAt}T23:59:59`) : null; if (startsAt && endsAt && endsAt <= startsAt) return toast.error("La période sélectionnée est invalide."); create.mutate({ businessId: business.id, name: form.name, code: form.code || null, discountType: form.type as "percentage" | "fixed", discountValue: form.type === "fixed" ? Math.round(value * 100) : value, minimumOrderCents: minimum, startsAt, endsAt, appliesToAll: form.productId === "all", productIds: form.productId === "all" ? [] : [Number(form.productId)] }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogTrigger asChild><Button><Plus size={17} /> Créer une promotion</Button></DialogTrigger><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Nouvelle promotion</DialogTitle></DialogHeader><form onSubmit={submit} className="cb-form compact"><div className="cb-form-row"><div><Label htmlFor="promo-name">Nom de l’offre</Label><Input id="promo-name" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Ex. Offre découverte" /></div><div><Label htmlFor="promo-code">Code (facultatif)</Label><Input id="promo-code" value={form.code} onChange={event => setForm({ ...form, code: event.target.value.toUpperCase() })} placeholder="BIENVENUE" /></div></div><div className="cb-form-row"><div><Label>Type</Label><Select value={form.type} onValueChange={value => setForm({ ...form, type: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="percentage">Pourcentage</SelectItem><SelectItem value="fixed">Montant fixe</SelectItem></SelectContent></Select></div><div><Label htmlFor="promo-value">Réduction</Label><Input id="promo-value" inputMode="decimal" value={form.value} onChange={event => setForm({ ...form, value: event.target.value })} placeholder={form.type === "fixed" ? "5" : "10"} /></div></div><div className="cb-form-row"><div><Label htmlFor="promo-start">Début</Label><Input id="promo-start" type="date" value={form.startsAt} onChange={event => setForm({ ...form, startsAt: event.target.value })} /></div><div><Label htmlFor="promo-end">Fin</Label><Input id="promo-end" type="date" value={form.endsAt} onChange={event => setForm({ ...form, endsAt: event.target.value })} /></div></div><div className="cb-form-row"><div><Label htmlFor="promo-minimum">Commande minimale</Label><Input id="promo-minimum" inputMode="decimal" value={form.minimum} onChange={event => setForm({ ...form, minimum: event.target.value })} placeholder="Facultatif" /></div><div><Label>Portée</Label><Select value={form.productId} onValueChange={value => setForm({ ...form, productId: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Toute la boutique</SelectItem>{products.map(row => <SelectItem key={row.product.id} value={String(row.product.id)}>{row.product.name}</SelectItem>)}</SelectContent></Select></div></div><Button type="submit" disabled={create.isPending}>Créer l’offre</Button></form></DialogContent></Dialog>;
}
