export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  canonicalOrigin: (process.env.CANONICAL_ORIGIN ?? "").replace(/\/$/, ""),
  publisherName: process.env.PUBLISHER_NAME ?? "",
  publisherAddress: process.env.PUBLISHER_ADDRESS ?? "",
  supportEmail: process.env.SUPPORT_EMAIL ?? "",
  dataRetentionDays: Number.parseInt(process.env.DATA_RETENTION_DAYS ?? "365", 10),
};
