import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { money, orderStatusLabel, shortDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { ChevronRight, Eye, Mail, Phone } from "lucide-react";

export function OrderDetails({ businessId, orderId }: { businessId: number; orderId: number }) { const detail = trpc.order.get.useQuery({ businessId, id: orderId }, { enabled: false }); return <Dialog><DialogTrigger asChild><Button variant="ghost" size="sm" onClick={() => detail.refetch()}><Eye size={15} /> Détail</Button></DialogTrigger><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Commande {detail.data?.order.orderNumber || ""}</DialogTitle></DialogHeader>{detail.isLoading ? <p>Chargement de la commande…</p> : detail.data ? <div className="cb-detail"><section><h4>Articles</h4>{detail.data.items.map(item => <div className="cb-detail-row" key={item.id}><span>{item.quantity} × {item.productName}</span><strong>{money(item.lineTotalCents)}</strong></div>)}<div className="cb-detail-total"><span>Total</span><strong>{money(detail.data.order.totalCents)}</strong></div></section><section><h4>Historique des statuts</h4><div className="cb-timeline">{detail.data.history.map(entry => <div key={entry.id}><i /><div><strong>{orderStatusLabel[entry.toStatus]}</strong><p>{entry.note || `Passage depuis ${entry.fromStatus ? orderStatusLabel[entry.fromStatus] : "la création"}`}</p><small>{shortDate(entry.createdAt)}</small></div></div>)}</div></section></div> : <p>Commande introuvable.</p>}</DialogContent></Dialog>; }

export function CustomerDetails({ businessId, customerId }: { businessId: number; customerId: number }) { const detail = trpc.customer.get.useQuery({ businessId, id: customerId }, { enabled: false }); return <Dialog><DialogTrigger asChild><Button variant="ghost" size="sm" onClick={() => detail.refetch()}><ChevronRight size={16} /> Voir la fiche</Button></DialogTrigger><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{detail.data ? `${detail.data.customer.firstName} ${detail.data.customer.lastName}` : "Fiche client"}</DialogTitle></DialogHeader>{detail.isLoading ? <p>Chargement de la fiche…</p> : detail.data ? <div className="cb-detail"><section className="cb-contact-sheet"><p><Mail size={15} /> {detail.data.customer.email}</p>{detail.data.customer.phone && <p><Phone size={15} /> {detail.data.customer.phone}</p>}{detail.data.customer.notes && <p>{detail.data.customer.notes}</p>}</section><section><h4>Historique de commandes</h4>{detail.data.orders.length ? detail.data.orders.map(order => <div className="cb-detail-row" key={order.id}><div><strong>{order.orderNumber}</strong><small>{shortDate(order.createdAt)} · {orderStatusLabel[order.status]}</small></div><b>{money(order.totalCents)}</b></div>) : <p>Aucune commande associée.</p>}</section></div> : <p>Client introuvable.</p>}</DialogContent></Dialog>; }
